name: Build Backend

on:
  workflow_dispatch:
    inputs:
      repo:
        description: 'Repo'
        required: true
        type: string
      commit:
        description: 'Commit'
        required: true
        type: string
      proto:
        description: 'Proto'
        required: true
        type: string
      path:
        description: 'Path'
        required: true
        type: string
      image:
        description: 'Image'
        required: true
        type: string
      version:
        description: 'Version'
        required: true
        type: string

jobs:
  build:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v3
      - uses: actions/github-script@v6
        env:
          VERSION_ID: ${{ inputs.version }}
          PAT: ${{ secrets.PAT }}
        with:
          script: |
            const script = require('./.github/scripts/start.js')
            await script('build')
      - uses: actions/checkout@v3
        with:
          repository: ${{ inputs.repo }}
          ref: ${{ inputs.commit }}
          token: ${{ secrets.PAT }}
      - uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ap-southeast-1
      - name: Download Proto
        env:
          Filename: ${{ inputs.proto }}.tar.gz
        run: |
          aws s3 cp s3://zhuhaolin.com-deploy/protos/$Filename $Filename
          tar -xzvf $Filename
          mv dist protos
      - uses: actions/setup-go@v1
        with:
          go-version: '1.19'
      - name: Build
        run: |
          go mod download
          CGO_ENABLED=0 GOOS=linux go build -a "app/${{ inputs.path }}/main.go"
      - uses: docker/setup-qemu-action@v1
      - uses: docker/setup-buildx-action@v1
      - uses: docker/login-action@v1
        with:
          registry: hkccr.ccs.tencentyun.com
          username: ${{ secrets.TENCENT_USERNAME }}
          password: ${{ secrets.TENCENT_PASSWORD }}
      - uses: docker/build-push-action@v2
        with:
          context: .
          file: ./build/Dockerfile
          push: true
          tags: hkccr.ccs.tencentyun.com/zhuhaolin.com/${{ inputs.image }}