name: Build Frontend

on:
  workflow_dispatch:
    inputs:
      repo:
        description: 'Repo'
        required: true
        type: string
      commit:
        description: 'Commit'
        required: true
        type: string
      version:
        description: 'Version'
        required: true
        type: string

jobs:
  build:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v3
        with:
          repository: ${{ inputs.repo }}
          ref: ${{ inputs.commit }}
          token: ${{ secrets.PAT }}
      - uses: actions/setup-node@v1
        with:
          node-version: '18.x'
      - uses: pnpm/action-setup@v2.0.1
        with:
          version: 'latest'
      - run: pnpm install
      - run: pnpm build
      - uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ap-southeast-1
      - name: Upload
        env:
          Filename: ${{ inputs.commit }}.tar.gz
        run: |
          tar -czvf $Filename dist
          aws s3 cp $Filename s3://zhuhaolin.com-deploy/frontend/$Filename --acl private
