name: Deploy Frontend

on:
  workflow_dispatch:
    inputs:
      path:
        description: 'Path'
        required: true
        type: string
      commit:
        description: 'Commit'
        required: true
        type: string
      version:
        description: 'Version'
        required: true
        type: string

jobs:
  init:
    runs-on: ubuntu-20.04
    steps: 
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
      - run: npm install axios
      - uses: actions/github-script@v6
        env:
          VERSION_ID: ${{ inputs.version }}
          PAT: ${{ secrets.PAT }}
        with:
          script: |
            const script = require('./.github/scripts/start.js')
            await script('deploy')
  deploy:
    runs-on: ubuntu-20.04
    needs: init
    steps:
      - uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ap-southeast-1
      - name: Download Dist
        env:
          Filename: ${{ inputs.commit }}.tar.gz
        run: |
          aws s3 cp s3://zhuhaolin.com-deploy/frontend/$Filename $Filename
          tar -xzvf $Filename
          mv dist ${{ inputs.path }}
      - uses: appleboy/scp-action@master
        with:
          host: ${{ secrets.SSH_HOST }}
          username: root
          key: ${{ secrets.SSH_KEY }}
          source: ${{ inputs.path }}
          target: "/var/www"
