name: Build NodeJS

on:
  workflow_dispatch:
    inputs:
      repo:
        description: 'Repo'
        required: true
        type: string
      commit:
        description: 'Commit'
        required: true
        type: string
      image:
        description: 'Image'
        required: true
        type: string
      version:
        description: 'Version'
        required: true
        type: string

jobs:
  init:
    runs-on: ubuntu-20.04
    steps: 
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
      - run: npm install axios
      - uses: actions/github-script@v6
        env:
          VERSION_ID: ${{ inputs.version }}
          PAT: ${{ secrets.PAT }}
        with:
          script: |
            const script = require('./.github/scripts/start.js')
            await script('build')
  build:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v3
        with:
          repository: ${{ inputs.repo }}
          ref: ${{ inputs.commit }}
          token: ${{ secrets.PAT }}
      - uses: docker/setup-qemu-action@v2
      - uses: docker/setup-buildx-action@v2
      - uses: docker/login-action@v2
        with:
          registry: hkccr.ccs.tencentyun.com
          username: ${{ secrets.TENCENT_USERNAME }}
          password: ${{ secrets.TENCENT_PASSWORD }}
      - uses: docker/build-push-action@v4
        with:
          context: .
          file: ./build/Dockerfile
          push: true
          tags: hkccr.ccs.tencentyun.com/zhuhaolin.com/${{ inputs.image }}
